{"match_website": "http://www.codeforces.com/contests", "match_name": "Codeforces Round #498 (Div. 3)", "match_writers": "", "match_start_date": "Jul/16/2018 17:35", "match_time_length": "02:00", "match_before_start": "05:55:10", "match_register": "x4541"}
{"match_website": "http://www.codeforces.com/contests", "match_name": "Codeforces Round #499 (Div. 1)", "match_writers": "", "match_start_date": "Jul/26/2018 18:05", "match_time_length": "02:00", "match_before_start": "10 days", "match_register": "no"}
{"match_website": "http://www.codeforces.com/contests", "match_name": "Codeforces Round #499 (Div. 2)", "match_writers": "", "match_start_date": "Jul/26/2018 18:05", "match_time_length": "02:00", "match_before_start": "10 days", "match_register": "no"}
{"match_website": "http://www.codeforces.com/contests", "match_name": "Codeforces Round #500 (Div. 1) [based on EJOI]", "match_writers": "", "match_start_date": "Jul/30/2018 11:05", "match_time_length": "02:00", "match_before_start": "2 weeks", "match_register": "no"}
{"match_website": "http://www.codeforces.com/contests", "match_name": "Codeforces Round #500 (Div. 2) [based on EJOI]", "match_writers": "", "match_start_date": "Jul/30/2018 11:05", "match_time_length": "02:00", "match_before_start": "2 weeks", "match_register": "no"}
{"match_website": "http://www.codeforces.com/contests", "match_name": "VK Cup 2018 - Final", "match_writers": "", "match_start_date": "Aug/12/2018 11:05", "match_time_length": "03:00", "match_before_start": "4 weeks", "match_register": "no"}
{"match_website": "http://www.codeforces.com/contests", "match_name": "Codeforces Round #498 (Div. 3)", "match_writers": "", "match_start_date": "Jul/16/2018 17:35", "match_time_length": "02:00", "match_before_start": "05:25:30", "match_register": "x4659"}
{"match_website": "http://www.codeforces.com/contests", "match_name": "Codeforces Round #499 (Div. 1)", "match_writers": "", "match_start_date": "Jul/26/2018 18:05", "match_time_length": "02:00", "match_before_start": "10 days", "match_register": "no"}
{"match_website": "http://www.codeforces.com/contests", "match_name": "Codeforces Round #499 (Div. 2)", "match_writers": "", "match_start_date": "Jul/26/2018 18:05", "match_time_length": "02:00", "match_before_start": "10 days", "match_register": "no"}
{"match_website": "http://www.codeforces.com/contests", "match_name": "Codeforces Round #500 (Div. 1) [based on EJOI]", "match_writers": "", "match_start_date": "Jul/30/2018 11:05", "match_time_length": "02:00", "match_before_start": "2 weeks", "match_register": "no"}
{"match_website": "http://www.codeforces.com/contests", "match_name": "Codeforces Round #500 (Div. 2) [based on EJOI]", "match_writers": "", "match_start_date": "Jul/30/2018 11:05", "match_time_length": "02:00", "match_before_start": "2 weeks", "match_register": "no"}
{"match_website": "http://www.codeforces.com/contests", "match_name": "VK Cup 2018 - Final", "match_writers": "", "match_start_date": "Aug/12/2018 11:05", "match_time_length": "03:00", "match_before_start": "4 weeks", "match_register": "no"}
